name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_db
          MYSQL_DATABASE: test_expensesdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Apply Flyway migrations
        run: |
          cd backend
          touch empty-flyway.conf
          mvn flyway:migrate \
            -Dflyway.configFiles=empty-flyway.conf \
            -Dflyway.url=jdbc:mysql://127.0.0.1:3306/test_expensesdb \
            -Dflyway.user=root \
            -Dflyway.password=test_db

      - name: Insert Test Data
        run: |
          mysql -h 127.0.0.1 -P 3306 -uroot -ptest_db test_expensesdb -e "
          INSERT INTO currencies (id, code, name, symbol) VALUES (2, 'GTQ', 'Quetzales', 'Q');
          INSERT INTO currencies (id, code, name, symbol) VALUES (3, 'USD', 'Dolares', '\$');
          INSERT INTO users (id, creation_date, currency_id, email, first_name, last_name, password, profile_picture, username, role)
          VALUES (0xF8DFFE3009ED4794ABC798A930C7B938, '2025-07-01', 1, 'coding.tamalito@gmail.com', null, null, '\$2a\$10\$FKYfPVP3XGCZswCBCKXKTeJqn8.cYJgU2T1YgWG0Tz3Z0tKn1r.ga', 'profilePicture', 'tamalito', 0);
          "

      - name: Run Backend Integration Tests
        run: |
          cd backend
          mvn verify -Pexecute-integration-tests

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          package-manager-cache: false

      - name: Install UI Dependencies
        run: |
          cd ui
          npm ci

      - name: Build UI
        run: |
          cd ui
          npm run build